# -------------------------------------------------------------------
# BART Simulation Study
#
# This script evaluates Bayesian additive regression trees (BART) using the
# datasets generated by scripts/BHARP_sim.R.
#
# For each scenario, the script:
#   1. reads the datasets generated by BHARP_sim.R;
#   2. fits BART to each dataset;
#   3. saves posterior samples and summaries; and
#   4. reports estimation operating characteristics.
#
# Before running:
#   - Set project_root to the local path of the cloned repository.
#   - Run scripts/BHARP_sim.R to generate the simulation datasets.
#   - Install the BART package.
#
# Dependencies:
#   functions/BART_model.R
#   scripts/simulation_config.R
#
# Output:
#   results/simulation/<scenario_name>/Output_BART/
# -------------------------------------------------------------------


project_root <- "YOURPATH/BHARP_release" # Please modify this path.
if (!dir.exists(project_root)) {
  stop("ERROR: project_root does not exist. Please modify the project_root path at the top of the script.")
}



source(   file.path(project_root, "functions", "BART_model.R"))
source(file.path(project_root, "scripts", "simulation_config.R"))


# ---- Run simulation scenarios ----
for (s in seq_along(scenario_list)) {
  scenario <- scenario_list[[s]]
  scenario_dir <- file.path(project_root, "results", "simulation", scenario$name)
  

  BART_results_dir <- file.path(scenario_dir, "Output_BART");
  if (!dir.exists(BART_results_dir)) {dir.create(BART_results_dir, showWarnings = FALSE, recursive = TRUE)}
  data_dir <- file.path(scenario_dir, "Data"); 

  log_file <- file.path(scenario_dir, paste0(scenario$name, "_BART_sim_results.txt"))
  log_message <- function(msg) {
    cat(paste0( msg, "\n"), file = log_file, append = TRUE)
  }
  
  log_message("====== Simulation setting ======")
  log_message(paste0("N_sim = ", N_sim, ", N_subgrp = ", N_subgrp, ", N_arm = ", N_arm))
  
  

  Theta_ <- scenario$Theta; ThetaVec<-as.vector(t(Theta_))
  cell_sizes <- scenario$cell_sizes
  
  
  # ---- Fit BART to the simulated datasets ----
  start<-Sys.time()
  cl <- parallel::makeCluster( max(1L, parallel::detectCores() - 2L), type="FORK")
  
  BART_results <- parallel::parLapply(cl, 1:N_sim, function(v) {
    seed_v<-44400000 + 1000 * s + v
    set.seed(seed_v)
    tryCatch({
    
      Dat<-read.csv(file.path(data_dir,paste0("DAT",v,".csv")))
      
      BART_result_v <- BART_analysis(
        Data = Dat,
        n_subgrp = N_subgrp,
        n_arm = N_arm,
        ndpost = 8000
      )
      
      thetamedian <- apply(BART_result_v, 2, median)
      thetaq750   <- apply(BART_result_v, 2, quantile, prob=0.750)
      thetaq250   <- apply(BART_result_v, 2, quantile, prob=0.250)
      theta_var   <- apply(BART_result_v, 2, var)
      
      return(
        list(
          DAT_number = v,
          theta = BART_result_v,
          thetamedian = thetamedian,
          thetaq250 = thetaq250,
          thetaq750 = thetaq750,
          theta_var = theta_var
        )
      )
    }, error=function(e) {
      return(list(DAT_number=v,error=TRUE, message=e$message))
    })
  })
  
  parallel::stopCluster(cl);
  
  scenario_time <- as.numeric(difftime(Sys.time(), start, units = "mins"))
  scenario_time <- round(scenario_time, 2)
  log_message(paste0("Total runtime: ", scenario_time, " minutes"))
  
  
  successful <- vapply(
    BART_results,
    function(x) is.null(x$error),
    logical(1)
  )
  BART_good_results <- BART_results[successful]
  
  saveRDS(BART_good_results, file = file.path(BART_results_dir,"BART_good_results_list.rds"))
  
  if (length(BART_good_results) == 0L) {
    log_message("No successful BART runs in this scenario.")
    next  
  }
  
  BART_thetamedian <- do.call(rbind, lapply(BART_good_results, "[[", "thetamedian"))
  BART_thetaq750 <- do.call(rbind,lapply(BART_good_results, "[[", "thetaq750"))
  BART_thetaq250 <- do.call(rbind,lapply(BART_good_results, "[[", "thetaq250"))
  BART_theta_var <- do.call(rbind,lapply(BART_good_results, "[[", "theta_var"))
  
  
  
  log_message("====== BART Results ======")
  # Root mean squared error
  RMSE <- matrix(sapply(
    seq_len(N_arm*N_subgrp), function(x) 
      sqrt(mean(  (BART_thetamedian[,x] - ThetaVec[x])^2 )  )
  ),nrow = N_arm,byrow=TRUE)
  log_message("RMSE:")
  log_message(paste(capture.output(print(round(RMSE,3))), collapse = "\n"))
  
  
  # Mean Absolute  Error
  MAE <- matrix(sapply(
    seq_len(N_arm*N_subgrp), function(x) 
      mean( abs( (BART_thetamedian[,x] - ThetaVec[x])  ) )  
  ),nrow = N_arm,byrow=TRUE)
  log_message("Mean Abs Error:")
  log_message(paste(capture.output(print(round(MAE,3))), collapse = "\n"))
  
  
  # Variance of Estimates
  VAR <- matrix(apply(BART_thetamedian,2,var),nrow = N_arm,byrow=TRUE)
  log_message("VAR of posterior median:")
  log_message(paste(capture.output(print(round(VAR,3))), collapse = "\n"))
  
  # IQR 
  IQR_mat <- BART_thetaq750 - BART_thetaq250
  IQR_mean <- matrix(colMeans(IQR_mat), nrow = N_arm, byrow = TRUE)
  log_message("Average posterior IQR of theta:")
  log_message(paste(capture.output(print(round(IQR_mean, 3))), collapse = "\n"))
}





