# -------------------------------------------------------------------------
# BHM Simulation Study
#
# This script evaluates the Bayesian hierarchical model (BHM) using the
# datasets generated by scripts/BHARP_sim.R.
#
# For each scenario, the script:
#   1. reads the datasets generated by BHARP_sim.R;
#   2. fits the BHM to each dataset;
#   3. saves posterior samples and summaries; and
#   4. reports estimation operating characteristics.
#
# Before running:
#   - Set project_root to the local path of the cloned repository.
#   - Run scripts/BHARP_sim.R to generate the simulation datasets.
#   - Install the rstan package.
#
# Dependencies:
#   Repository files:
#     functions/BHM_model.R
#     scripts/simulation_config.R
#
# Output:
#   results/simulation/<scenario_name>/Output_BHM/
# -------------------------------------------------------------------------




project_root <- "YOURPATH/BHARP_release" # Please modify this path.

if (!dir.exists(project_root)) {
  stop("ERROR: project_root does not exist. Please modify the project_root path at the top of the script.")
}



source(   file.path(project_root, "functions", "BHM_model.R"))
source(file.path(project_root, "scripts", "simulation_config.R"))

options(mc.cores = 1)




# ---- Run simulation scenarios ----

for (s in seq_along(scenario_list)) {
  scenario <- scenario_list[[s]]
  
  scenario_dir <- file.path(project_root, "results", "simulation", scenario$name)
  BHM_results_dir <- file.path(scenario_dir, "Output_BHM");
  if (!dir.exists(BHM_results_dir)) {dir.create(BHM_results_dir, showWarnings = FALSE, recursive = TRUE)}

  data_dir <- file.path(scenario_dir, "Data"); 

  log_file <- file.path(scenario_dir, paste0(scenario$name, "_BHM_sim_results.txt"))
  log_message <- function(msg) {
    cat(paste0( msg, "\n"), file = log_file, append = TRUE)
  }
  
  log_message("====== Simulation setting ======")
  log_message(paste0("N_sim = ", N_sim, ", N_subgrp = ", N_subgrp, ", N_arm = ", N_arm))
  log_message("Hyperparameters:")
  log_message(paste(capture.output(str(BHM_hyperparam)), collapse = "\n"))
  

  Theta_ <- scenario$Theta; ThetaVec<-as.vector(t(Theta_))
  cell_sizes <- scenario$cell_sizes
  
  
  # ---- Conduct BHM ----
  start<-Sys.time()
  cl <- parallel::makeCluster( max(1L, parallel::detectCores() - 2L), type="FORK")
  
  BHM_results <- parLapply(cl, 1:N_sim, function(v) {
    seed_v<-22200000 + 1000 * s + v
    set.seed(seed_v)
    
    tryCatch({
      Dat<-read.csv(file.path(data_dir,paste0("DAT",v,".csv")))

      BHM_result_v <- BHM_analysis(
        Data = Dat,
        n_subgrp = N_subgrp,
        n_arm = N_arm,
        hyperparam = BHM_hyperparam,
        seed = seed_v
      )
      
      thetamedian <- apply(BHM_result_v, 2, median)
      thetaq750   <- apply(BHM_result_v, 2, quantile, prob=0.750)
      thetaq250   <- apply(BHM_result_v, 2, quantile, prob=0.250)
      theta_var <- apply(BHM_result_v, 2, var)
      
      return(list(DAT_number=v,
                  theta=BHM_result_v, 
                  thetamedian=thetamedian, 
                  thetaq250=thetaq250,
                  thetaq750=thetaq750,
                  theta_var=theta_var))
    }, error=function(e) {
        return(list(DAT_number=v,error=TRUE, message=e$message))
      }
    )
  }
)
  
  parallel::stopCluster(cl)
  
  
  scenario_time <- as.numeric(difftime(Sys.time(), start, units = "mins"))
  scenario_time <- round(scenario_time, 2)
  log_message(paste0("Total runtime: ", scenario_time, " minutes"))
  
  
  BHM_good_results <- BHM_results[ sapply(BHM_results, function(x) is.null(x$error)) ]
  if (length(BHM_good_results) == 0L) {
    log_message("No successful BHM runs in this scenario.")
    next
  }
  saveRDS(BHM_good_results, file = file.path(BHM_results_dir,"BHM_good_results_list.rds"))
  
  
  if (length(BHM_good_results) == 0) {
    log_message("No successful BHM runs in this scenario.")
    next  
  }
  
  BHM_thetamedian <- do.call(rbind, lapply(BHM_good_results, "[[", "thetamedian"))
  BHM_thetaq750 <- do.call(rbind,lapply(BHM_good_results, "[[", "thetaq750"))
  BHM_thetaq250 <- do.call(rbind,lapply(BHM_good_results, "[[", "thetaq250"))
  BHM_theta_var <- do.call(rbind,lapply(BHM_good_results, "[[", "theta_var"))
  
  
  
  log_message("====== BHM Results ======")
  
  #RMSE  
  RMSE <- matrix(sapply(
    seq_len(N_arm*N_subgrp), function(x) 
      sqrt(mean(  (BHM_thetamedian[,x] - ThetaVec[x])^2 )  )
  ),nrow = N_arm,byrow=TRUE)
  log_message("RMSE:")
  log_message(paste(capture.output(print(round(RMSE,3))), collapse = "\n"))
  
  
  # Mean Absolute  Error
  MAE <- matrix(sapply(
    seq_len(N_arm*N_subgrp), function(x) 
      mean( abs( (BHM_thetamedian[,x] - ThetaVec[x])  ) )  
  ),nrow = N_arm,byrow=TRUE)
  log_message("Mean Abs Error:")
  log_message(paste(capture.output(print(round(MAE,3))), collapse = "\n"))
  
  
  
  # Variance of Estimates
  VAR <- matrix(apply(BHM_thetamedian,2,var),nrow = N_arm,byrow=TRUE)
  log_message("VAR of posterior median:")
  log_message(paste(capture.output(print(round(VAR,3))), collapse = "\n"))
  

  # IQR 
  IQR_mat <- BHM_thetaq750 - BHM_thetaq250
  IQR_mean <- matrix(colMeans(IQR_mat), nrow = N_arm, byrow = TRUE)
  log_message("Average posterior IQR of theta:")
  log_message(paste(capture.output(print(round(IQR_mean, 3))), collapse = "\n"))
  
  
  # posterior variance
  PosteriorVar_mean <- matrix(colMeans(BHM_theta_var), nrow = N_arm, byrow = TRUE)
  log_message("Average posterior variance of theta (within simulations):")
  log_message(paste(capture.output(print(round(PosteriorVar_mean, 3))), collapse = "\n"))
}



