# -------------------------------------------------------------------------
# BLAST Simulation Study
#
# This script evaluates the BLAST method using the datasets generated by
# scripts/BHARP_sim.R. Using the same datasets allows direct comparison
# between BLAST and BHARP under each simulation scenario.
#
# For each scenario, the script:
#   1. reads the datasets generated by BHARP_sim.R;
#   2. fits the BLAST model to each dataset;
#   3. selects the number of mixture components using DIC;
#   4. summarizes posterior estimates and subgroup clustering; and
#   5. reports estimation operating characteristics.
#
# Before running:
#   - Set project_root to the local path of the cloned repository.
#   - Run scripts/BHARP_sim.R to generate the simulation datasets.
#   - Install the R packages listed under "Dependencies" below.
#
# Dependencies:
#   R packages:
#     rstan parallel
#
#   Repository files:
#     functions/BLAST_model.R
#     functions/helper_cocluster.R
#     scripts/simulation_config.R
#
# Output:
#   Posterior summaries and operating characteristics are written to:
#
#     results/simulation/<scenario_name>/Output_BLAST/
#
#   Scenario-level summaries are written to:
#
#     results/simulation/<scenario_name>/<scenario_name>_BLAST_sim_results.txt
#
# -------------------------------------------------------------------------


# ---- Set root directory and load packages ----

project_root <- "YOURPATH/BHARP_release" #please modify this
if (!dir.exists(project_root)) {
  stop("ERROR: project_root does not exist. Please modify the project_root path at the top of the script.")
}

source(file.path(project_root, "functions", "helper_cocluster.R"))
source(   file.path(project_root, "functions", "BLAST_model.R"))
source(file.path(project_root, "scripts", "simulation_config.R"))

options(mc.cores = 1)




# ---- Run simulations ----

for (s in seq_along(scenario_list)) {
  scenario <- scenario_list[[s]]
  
  # ---- Directory ----
  
  scenario_dir <- file.path(
    project_root,
    "results",
    "simulation",
    scenario$name
  )
  
  BLAST_results_dir <- file.path(
    scenario_dir,
    "Output_BLAST"
  )
  
  if (!dir.exists(BLAST_results_dir)) {
    dir.create(BLAST_results_dir, showWarnings = FALSE, recursive = TRUE)
  }
  
  # These datasets are generated by BHARP_sim.R.
  data_dir <- file.path(
    scenario_dir,
    "Data"
  )
  
  log_file <- file.path(
    scenario_dir,
    paste0(
      scenario$name,
      "_BLAST_sim_results.txt"
    )
  )
  
  log_message <- function(msg) {
    cat(paste0( msg, "\n"), file = log_file, append = TRUE)
  }
  
  log_message("====== Simulation setting ======")
  log_message(paste0("N_sim = ", N_sim, ", N_subgrp = ", N_subgrp, ", N_arm = ", N_arm))
  log_message("Hyperparameters:")
  log_message(paste(capture.output(str(BLAST_hyperparam)), collapse = "\n"))
  

  Theta_ <- scenario$Theta; ThetaVec<-as.vector(t(Theta_))
  cell_sizes <- scenario$cell_sizes
  


  

  # ---- Fit BLAST----
  start <- Sys.time()
  cl <- parallel::makeCluster( max(1L, parallel::detectCores() - 2L), type="FORK")

  BLAST_results <- parallel::parLapply(cl, 1:N_sim, function(v) { 
      seed_v<-33300000 + 1000 * s + v
      set.seed(seed_v)
      tryCatch(
        {
          Dat <- read.csv(file.path(data_dir, paste0("DAT", v, ".csv")))
          BLAST <- BLAST_analysis(
            Data       = Dat,
            n_subgrp   = N_subgrp,
            hyperparam = BLAST_hyperparam,
            seed       = seed_v
          )

          BLAST_result_v <- BLAST$theta_posterior
          BLAST_q_v      <- BLAST$q
          BLAST_iz_v     <- BLAST$iz_cocluster_prob
          
          thetamedian <- apply(BLAST_result_v, 2, median)
          thetaq750   <- apply(BLAST_result_v, 2, quantile, prob = 0.750)
          thetaq250   <- apply(BLAST_result_v, 2, quantile, prob = 0.250)
          theta_var   <- apply(BLAST_result_v, 2, var)
          
          list(
            DAT_number        = v,
            q                 = BLAST_q_v,
            theta             = BLAST_result_v,
            thetamedian       = thetamedian,
            thetaq250         = thetaq250,
            thetaq750         = thetaq750,
            theta_var         = theta_var,
            iz_cocluster_prob = BLAST_iz_v
          )
        }, 
        error = function(e) {
          list(DAT_number = v, error = TRUE, message = e$message)
        }
      )
    }
  )
  parallel::stopCluster(cl)
  scenario_time <- as.numeric(difftime(Sys.time(), start, units = "mins"))
  scenario_time <- round(scenario_time, 2)
  log_message(paste0("Total runtime: ", scenario_time, " minutes"))
  
  BLAST_good_results <- BLAST_results[ sapply(BLAST_results, function(x) is.null(x$error)) ]
  saveRDS(BLAST_good_results, file = file.path(BLAST_results_dir,"BLAST_good_results_list.rds"))
  
  if (length(BLAST_good_results) == 0) {
    log_message("No successful BLAST runs in this scenario.")
    next  
  }
  
  
  BLAST_thetamedian <- do.call(rbind, lapply(BLAST_good_results, "[[", "thetamedian"))
  BLAST_thetaq750 <- do.call(rbind,lapply(BLAST_good_results, "[[", "thetaq750"))
  BLAST_thetaq250 <- do.call(rbind,lapply(BLAST_good_results, "[[", "thetaq250"))
  BLAST_theta_var <- do.call(rbind,lapply(BLAST_good_results, "[[", "theta_var"))
  BLAST_q<-do.call(c,lapply(BLAST_good_results, "[[", "q"))
  BLAST_coCluster_list <- lapply(BLAST_good_results, "[[", "iz_cocluster_prob")
  
  
  log_message("====== BLAST Results ======")
  #Root mean squared error
  RMSE <- matrix(sapply(
    seq_len(N_arm*N_subgrp), function(x) 
      sqrt(mean(  (BLAST_thetamedian[,x] - ThetaVec[x])^2 )  )
  ),nrow = N_arm,byrow=TRUE)
  log_message("RMSE:")
  log_message(paste(capture.output(print(round(RMSE,3))), collapse = "\n"))
  
  
  # Mean Absolute  Error
  MAE <- matrix(sapply(
    seq_len(N_arm*N_subgrp), function(x) 
      mean( abs( (BLAST_thetamedian[,x] - ThetaVec[x])  ) )  
  ),nrow = N_arm,byrow=TRUE)
  log_message("Mean Abs Error:")
  log_message(paste(capture.output(print(round(MAE,3))), collapse = "\n"))
  
  
  # Variance of Estimates
  VAR <- matrix(apply(BLAST_thetamedian,2,var),nrow = N_arm,byrow=TRUE)
  log_message("VAR of posterior median:")
  log_message(paste(capture.output(print(round(VAR,3))), collapse = "\n"))
  
  
  # IQR 
  IQR_mat <- BLAST_thetaq750 - BLAST_thetaq250
  IQR_mean <- matrix(colMeans(IQR_mat), nrow = N_arm, byrow = TRUE)
  log_message("Average posterior IQR of theta:")
    log_message(paste(capture.output(print(round(IQR_mean, 3))), collapse = "\n"))

  
  # posterior variance
  PosteriorVar_mean <- matrix(colMeans(BLAST_theta_var), nrow = N_arm, byrow = TRUE)
  log_message("Average posterior variance of theta (within simulations):")
  log_message(paste(capture.output(print(round(PosteriorVar_mean, 3))), collapse = "\n"))
  
  
  # q 
  log_message("Distribution of selected q:")
  log_message(paste(capture.output(print(round(prop.table(table(BLAST_q)), 3))), collapse = "\n"))
  
  # Average Cocluster Probability for BLAST
  Avg_coCluster_BLAST <- vector("list", N_arm)
  n_trials <- length(BLAST_coCluster_list)
  
  for (i in seq_len(N_arm) ){
    mats_for_arm_i <- lapply(BLAST_coCluster_list, function(xx) xx[[i]])
    sum_mat <- Reduce("+", mats_for_arm_i)
    avg_mat <- round(sum_mat / n_trials, 3)
    
    Avg_coCluster_BLAST[[i]] <- avg_mat
  }
  log_message("BLAST Coclustering Probability:")
  log_message(paste(capture.output(print(Avg_coCluster_BLAST)), collapse = "\n"))

}
