# -------------------------------------------------------------------------
# IND Simulation Study
#
# This script evaluates the independent analysis (IND) method using the
# datasets generated by scripts/BHARP_sim.R.
#
# For each scenario, the script:
#   1. reads the datasets generated by BHARP_sim.R;
#   2. fits the IND model to each dataset;
#   3. saves posterior summaries; and
#   4. reports estimation operating characteristics.
#
# Before running:
#   - Set project_root to the local path of the cloned repository.
#   - Run scripts/BHARP_sim.R to generate the simulation datasets.
#   - Install the rstan package.
#
# Dependencies:
#   R package:
#     rstan
#
#   Repository files:
#     functions/IND_model.R
#     scripts/simulation_config.R
#
# Output:
#   Results are written to:
#
#     results/simulation/<scenario_name>/Output_IND/
# -------------------------------------------------------------------------


project_root <- "YOURPATH/BHARP_release" #please modify this
if (!dir.exists(project_root)) {
  stop("ERROR: project_root does not exist. Please modify the project_root path at the top of the script.")
}

#load source file
source(   file.path(project_root, "functions", "IND_model.R"))
source(file.path(project_root, "scripts", "simulation_config.R"))

options(mc.cores = 1)





# ---- Run simulation scenarios ----

for (s in seq_along(scenario_list)) {
  scenario <- scenario_list[[s]]
  scenario_dir <- file.path(project_root, "results", "simulation", scenario$name)
  IND_results_dir <- file.path(scenario_dir, "Output_IND");
  if (!dir.exists(IND_results_dir)) {dir.create(IND_results_dir, showWarnings = FALSE, recursive = TRUE)}
  data_dir <- file.path(scenario_dir, "Data"); 
  log_file <- file.path(scenario_dir, paste0(scenario$name, "_IND_sim_results.txt"))
  log_message <- function(msg) {
    cat(paste0( msg, "\n"), file = log_file, append = TRUE)
  }
  
  Theta_ <- scenario$Theta; ThetaVec<-as.vector(t(Theta_))
  cell_sizes <- scenario$cell_sizes

  
  # ---- Conduct IND----
  start<-Sys.time()
  
  cl <- parallel::makeCluster( max(1L, parallel::detectCores() - 2L), type="FORK")
  
  IND_results <- parallel::parLapply(cl, 1:N_sim, function(v) {
    seed_v<-11100000 + 1000 * s + v
    set.seed(seed_v)
    tryCatch({
      Dat<-read.csv(file.path(data_dir,paste0("DAT",v,".csv")))
      IND_result_v <- IND_analysis(
        Data=Dat,
        n_subgrp=N_subgrp,
        n_arm=N_arm,
        hyperparam=IND_hyperparam,
        seed=seed_v
      )
      
      thetamedian <- apply(IND_result_v, 2, median)
      thetaq750   <- apply(IND_result_v, 2, quantile, prob=0.750)
      thetaq250   <- apply(IND_result_v, 2, quantile, prob=0.250)
      theta_var <- apply(IND_result_v, 2, var)
      
      return(
        list(
          DAT_number=v,
          theta=IND_result_v, 
          thetamedian=thetamedian, 
          thetaq250=thetaq250,
          thetaq750=thetaq750,
          theta_var=theta_var
        )
      )
    }, 
    error=function(e) {
      return(list(DAT_number=v,error=TRUE, message=e$message))
    }
   )
  }
)
  
  parallel::stopCluster(cl);
  
  scenario_time <- as.numeric(difftime(Sys.time(), start, units = "mins"))
  scenario_time <- round(scenario_time, 2)
  log_message(paste0("Total runtime: ", scenario_time, " minutes"))
  
  IND_good_results <- IND_results[ sapply(IND_results, function(x) is.null(x$error)) ]
  saveRDS(IND_good_results, file = file.path(IND_results_dir,"IND_good_results_list.rds"))
  
  if (length(IND_good_results) == 0L) {
    log_message("No successful IND runs in this scenario.")
    next  
  }
  

  IND_thetamedian <- do.call(rbind, lapply(IND_good_results, "[[", "thetamedian"))
  IND_thetaq750 <- do.call(rbind,lapply(IND_good_results, "[[", "thetaq750"))
  IND_thetaq250 <- do.call(rbind,lapply(IND_good_results, "[[", "thetaq250"))
  IND_theta_var <- do.call(rbind,lapply(IND_good_results, "[[", "theta_var"))
  

  
  
  log_message("====== IND Results ======")
  #Root mean squared error
  RMSE <- matrix(sapply(
    seq_len(N_arm*N_subgrp), function(x) 
      sqrt(mean(  (IND_thetamedian[,x] - ThetaVec[x])^2 )  )
  ),nrow = N_arm,byrow=TRUE)
  log_message("RMSE:")
  log_message(paste(capture.output(print(round(RMSE,3))), collapse = "\n"))

  
  # Mean Absolute  Error
  MAE <- matrix(sapply(
    seq_len(N_arm*N_subgrp), function(x) 
      mean( abs( (IND_thetamedian[,x] - ThetaVec[x])  ) )  
  ),nrow = N_arm,byrow=TRUE)
  log_message("Mean Abs Error:")
  log_message(paste(capture.output(print(round(MAE,3))), collapse = "\n"))
  
  
  # Variance of Estimates
  VAR <- matrix(apply(IND_thetamedian,2,var),nrow = N_arm,byrow=TRUE)
  log_message("VAR of posterior median:")
  log_message(paste(capture.output(print(round(VAR,3))), collapse = "\n"))

  # IQR 
  IQR_mat <- IND_thetaq750 - IND_thetaq250
  IQR_mean <- matrix(colMeans(IQR_mat), nrow = N_arm, byrow = TRUE)
  log_message("Average posterior IQR of theta:")
  log_message(paste(capture.output(print(round(IQR_mean, 3))), collapse = "\n"))

  
  # posterior variance 
  PosteriorVar_mean <- matrix(colMeans(IND_theta_var), nrow = N_arm, byrow = TRUE)
  log_message("Average posterior variance of theta (within simulations):")
  log_message(paste(capture.output(print(round(PosteriorVar_mean, 3))), collapse = "\n"))
  
}






